### PR TITLE
WIP: Refactor + Convert to RapidJson + Digest Schema

### PR DESCRIPTION
**Pull request by mster**
Work in progress.

### CODE REVIEW

**Comment by mster** [comment]
> TODO:
> 
> * Output path formatter and checker.
>   
>   * Check for existing file.
>   * Do not allow file overwrites.
> * Set unique digest identifier. (timestamp?)

* File path utilities
    * check if input.json path is valid before generating backup parameters.
    * check if output path is valid.

**Comment by mster** [comment]
#14 is completed via ff0fadc76043d2852060006c616c717c4056e39e

**Comment by mster** [comment]
TODO:
 * Output path ~formatter and~ checker.
 * ~Check for existing file.~
    * Do not allow file overwrites.
 * ~Set unique digest identifier. (timestamp?)~
  * Check if input.json path is valid before generating backup parameters. (main)

**Comment by mster** [comment]
**Saving path utils for another branch.**

Will remove `directoryTree.cpp/.hpp` and `json.cpp/hpp` and merge once approved. @nick-nuti

**Review by nick-nuti — APPROVED** [review]

**Pull request merged**
